# Generated by Django 5.2.5 on 2025-09-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_page_button_text_page_button_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='button_color',
            field=models.CharField(blank=True, default='#0077c2', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='classic_menu_color',
            field=models.CharField(blank=True, default='#222', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='classic_menu_text',
            field=models.CharField(blank=True, default='Classic Menu', max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='classic_menu_url',
            field=models.CharField(blank=True, default='/', max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='main_pages_color',
            field=models.CharField(blank=True, default='#222', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='main_pages_text',
            field=models.CharField(blank=True, default='Main Pages', max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='main_pages_url',
            field=models.CharField(blank=True, default='#', max_length=200),
        ),
    ]
