# Generated by Django 5.2.5 on 2025-09-03 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_page_button_color_page_classic_menu_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='button_color',
        ),
        migrations.RemoveField(
            model_name='page',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='page',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='page',
            name='classic_menu_color',
        ),
        migrations.RemoveField(
            model_name='page',
            name='classic_menu_text',
        ),
        migrations.RemoveField(
            model_name='page',
            name='classic_menu_url',
        ),
        migrations.RemoveField(
            model_name='page',
            name='main_pages_color',
        ),
        migrations.RemoveField(
            model_name='page',
            name='main_pages_text',
        ),
        migrations.RemoveField(
            model_name='page',
            name='main_pages_url',
        ),
        migrations.CreateModel(
            name='MenuButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('color', models.CharField(blank=True, default='#0077c2', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='cms.page')),
            ],
        ),
    ]
