# Generated by Django 5.2.5 on 2025-09-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_remove_page_button_color_remove_page_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('color', models.CharField(blank=True, default='#0077c2', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Header Button',
                'verbose_name_plural': 'Header Buttons',
                'ordering': ['order'],
            },
        ),
    ]
