# Generated by Django 5.2.5 on 2025-09-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_block_alter_menubutton_options_pageblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
