# Generated by Django 5.2.5 on 2025-09-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Setting', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='key',
            field=models.CharField(default='default_key', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
