# Generated by Django 5.2.5 on 2025-09-08 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(default='primary', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('page', 'Page')], default='page', max_length=10)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='cms.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='HeaderButton',
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['order']},
        ),
        migrations.DeleteModel(
            name='MenuButton',
        ),
    ]
