# Generated by Django 5.2.5 on 2025-09-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_button_delete_headerbutton_alter_block_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('page', 'Page')], max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='button',
            name='locations',
            field=models.ManyToManyField(blank=True, to='cms.buttonlocation'),
        ),
    ]
