# Generated by Django 5.2.5 on 2025-09-08 09:54

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_buttonlocation_button_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='locations',
        ),
        migrations.AddField(
            model_name='button',
            name='locations',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('header', 'Header'), ('footer', 'Footer'), ('page', 'Page')], max_length=18),
        ),
    ]
