# Generated by Django 5.2.5 on 2025-09-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_remove_button_locations_button_locations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ButtonLocation',
        ),
    ]
