# Generated by Django 5.2.5 on 2025-09-08 11:11

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_delete_buttonlocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={},
        ),
        migrations.RemoveField(
            model_name='button',
            name='location',
        ),
        migrations.RemoveField(
            model_name='button',
            name='page',
        ),
        migrations.AlterField(
            model_name='button',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='button',
            name='locations',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('header', 'Header'), ('footer', 'Footer'), ('page', 'Page')], max_length=18),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
