# Generated by Django 5.2.5 on 2025-09-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_alter_block_options_remove_button_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='buttons',
            field=models.ManyToManyField(blank=True, to='cms.button'),
        ),
    ]
