# Generated by Django 5.2.5 on 2025-09-09 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_page_buttons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['order']},
        ),
    ]
