# Generated by Django 5.2.5 on 2025-09-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_alter_block_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
