# Generated by Django 5.2.5 on 2025-09-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_alter_button_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='button',
            name='name_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='button',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='button',
            name='url_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='button',
            name='url_ro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='button',
            name='url_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
