# Generated by Django 5.2.5 on 2025-09-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_button_name_en_button_name_ro_button_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='url_en',
        ),
        migrations.RemoveField(
            model_name='button',
            name='url_ro',
        ),
        migrations.RemoveField(
            model_name='button',
            name='url_ru',
        ),
    ]
