# Generated by Django 5.2.5 on 2025-09-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_remove_button_url_en_remove_button_url_ro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='locations',
        ),
    ]
