# Generated by Django 5.2.5 on 2025-09-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_remove_button_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
