# Generated by Django 5.2.5 on 2025-09-23 10:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_alter_blogpost_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
