# Generated by Django 5.2.5 on 2025-09-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_alter_blogpost_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='is_published',
        ),
    ]
