# Generated by Django 5.2.5 on 2025-09-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_pricingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='cta_text',
            field=models.CharField(default='Get Started', max_length=50),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='cta_url',
            field=models.CharField(blank=True, default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='period',
            field=models.CharField(default='Monthly', max_length=50),
        ),
    ]
