# Generated by Django 5.2.7 on 2025-10-27 10:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_pricingplan_cta_text_pricingplan_cta_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={},
        ),
        migrations.RemoveField(
            model_name='block',
            name='order',
        ),
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.AddField(
            model_name='block',
            name='message_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
