# Generated by Django 5.2.7 on 2025-11-14 19:02

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_alter_block_options_remove_block_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Block', 'verbose_name_plural': 'Blocks'},
        ),
        migrations.RemoveField(
            model_name='block',
            name='message_id',
        ),
        migrations.AlterField(
            model_name='block',
            name='content',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='BlockTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cms.block')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.language')),
            ],
            options={
                'verbose_name': 'Block Translation',
                'verbose_name_plural': 'Block Translations',
                'unique_together': {('block', 'language')},
            },
        ),
    ]
