# Generated by Django 5.2.7 on 2025-11-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_language_alter_block_options_remove_block_message_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingPlan',
        ),
    ]
