# Generated by Django 5.2.7 on 2025-11-22 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_block_slug_alter_block_content_alter_blogpost_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blocktranslation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='button',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='blocktranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pageblock',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='block',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='button',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='page',
            name='buttons',
        ),
        migrations.AlterField(
            model_name='block',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blocktranslation',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.block'),
        ),
        migrations.AlterField(
            model_name='blocktranslation',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='blocktranslation',
            name='title',
        ),
    ]
