# Generated by Django 5.2.7 on 2025-12-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_alter_block_options_alter_blocktranslation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
