# Generated by Django 5.2.7 on 2025-12-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0033_alter_button_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='value',
            field=models.CharField(max_length=500),
        ),
    ]
