# Generated by Django 5.2.7 on 2025-12-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0034_alter_sitesettings_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_role', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='testimonials')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='TestimonialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='testimonials', max_length=200)),
                ('title', models.CharField(default='Our partners', max_length=200)),
                ('button_text', models.CharField(default='View All', max_length=100)),
                ('button_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Testimonial Section',
                'verbose_name_plural': 'Testimonial Section',
            },
        ),
    ]
