# Generated by Django 5.2.7 on 2025-12-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_testimonial_testimonialsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestimonialSection',
        ),
    ]
